version: '3'

services:
  simmulation:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/simmulation
    working_dir: /simmulation
#    command: ['mvn', 'spring-boot:run']
